import { SUPABASE_ANON_KEY, SUPABASE_URL } from './supabase-config.js';
const $=s=>document.querySelector(s);
const headers={apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,'Content-Type':'application/json'};
const sessionToken=()=>JSON.parse(localStorage.getItem('mainstreet.staff-session.v3')||'null')?.token||null;
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const safe=v=>String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
async function rpc(name,body){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers,body:JSON.stringify(body)});const text=await response.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!response.ok)throw Error(data?.message||data?.hint||'Request failed');return data}
function dateValue(date){const d=new Date(date);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function notify(message){const box=$('#toastRegion');if(!box)return;const row=document.createElement('div');row.className='toast';row.textContent=message;box.append(row);setTimeout(()=>row.remove(),3000)}

function setupExpenseLedger(){const form=$('#expenseForm');if(!form||$('#expenseLedgerPanel'))return;const end=dateValue(new Date());const start=dateValue(new Date(Date.now()-29*86400000));const panel=document.createElement('section');panel.id='expenseLedgerPanel';panel.className='account-panel';panel.innerHTML=`<div class="account-head"><div><p class="eyebrow">Expense statement</p><h3>Expense ledger</h3></div><button id="refreshExpenseLedger" class="btn secondary" type="button">Refresh</button></div><div class="account-date-grid"><label><span>From</span><input id="expenseLedgerFrom" type="date" value="${start}"></label><label><span>To</span><input id="expenseLedgerTo" type="date" value="${end}"></label></div><div id="expenseLedgerSummary" class="account-summary-cards"></div><div id="expenseLedgerList" class="account-list"></div>`;form.after(panel);$('#refreshExpenseLedger').onclick=loadExpenseLedger;$('#expenseLedgerFrom').onchange=loadExpenseLedger;$('#expenseLedgerTo').onchange=loadExpenseLedger;loadExpenseLedger()}
async function loadExpenseLedger(){try{const rows=await rpc('get_expenses',{p_token:sessionToken(),p_from:$('#expenseLedgerFrom').value,p_to:$('#expenseLedgerTo').value})||[];const total=rows.reduce((sum,row)=>sum+Number(row.amount||0),0);$('#expenseLedgerSummary').innerHTML=`<article><span>Total expenses</span><b>${money(total)}</b></article><article><span>Entries</span><b>${rows.length}</b></article>`;$('#expenseLedgerList').innerHTML=rows.length?rows.map(row=>`<div class="expense-ledger-row"><div><b>${safe(row.description)}</b><small>${safe(row.category)} · ${safe(row.expense_date)}</small></div><strong>${money(row.amount)}</strong></div>`).join(''):'<div class="account-empty">No expenses in selected date range</div>'}catch(error){notify(error.message)}}

function setupCustomerSummary(){const filters=$('.ledger-filters');if(!filters||$('#customerSummaryPanel'))return;const panel=document.createElement('section');panel.id='customerSummaryPanel';panel.className='account-panel customer-summary-panel';panel.innerHTML='<div class="account-head"><div><p class="eyebrow">All accounts</p><h3>Customer balances</h3></div><button id="refreshCustomerSummary" class="btn secondary" type="button">Refresh</button></div><p class="account-note">Tap any customer to open the last 30 days ledger.</p><div id="customerSummaryStats" class="account-summary-cards"></div><div id="customerSummaryList" class="account-list"></div>';filters.after(panel);$('#refreshCustomerSummary').onclick=loadCustomerSummary;loadCustomerSummary()}
async function loadCustomerSummary(){try{const rows=await rpc('get_customer_summary',{p_token:sessionToken()})||[];const receivable=rows.filter(row=>Number(row.balance)>0).reduce((sum,row)=>sum+Number(row.balance),0);const greenCount=rows.filter(row=>Number(row.balance)<=0).length;$('#customerSummaryStats').innerHTML=`<article><span>Total customers</span><b>${rows.length}</b></article><article><span>Total receivable</span><b class="balance-debit">${money(receivable)}</b></article><article><span>Settled / credit</span><b class="balance-credit">${greenCount}</b></article>`;$('#customerSummaryList').innerHTML=rows.length?rows.map(row=>{const balance=Number(row.balance||0);const color=balance>0?'balance-debit':'balance-credit';const status=balance>0?'Debit':'Settled / Credit';return `<button type="button" class="customer-summary-row" data-name="${safe(row.name)}" data-phone="${safe(row.phone||'')}"><div><b>${safe(row.name)}</b><small>${safe(row.phone||'No mobile')} · ${status}</small></div><strong class="${color}">${money(balance)}</strong></button>`}).join(''):'<div class="account-empty">No customers found</div>';$('#customerSummaryList').querySelectorAll('.customer-summary-row').forEach(button=>button.onclick=()=>openCustomerLedger(button.dataset.name,button.dataset.phone))}catch(error){notify(error.message)}}
function openCustomerLedger(name,phone){const end=new Date();const start=new Date();start.setDate(end.getDate()-29);$('#ledgerCustomer').value=name;$('#ledgerPhone').value=phone||'';$('#ledgerFrom').value=dateValue(start);$('#ledgerTo').value=dateValue(end);$('#generateLedger').click();setTimeout(()=>$('#ledgerList')?.scrollIntoView({behavior:'smooth',block:'start'}),250)}

$('#openExpense')?.addEventListener('click',()=>setTimeout(setupExpenseLedger,80));
$('#openLedger')?.addEventListener('click',()=>setTimeout(setupCustomerSummary,80));
