import { SUPABASE_ANON_KEY, SUPABASE_URL } from './supabase-config.js';

const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const headers={apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,'Content-Type':'application/json'};
const sessionKey='mainstreet.staff-session.v3';
const queueKey='mainstreet.counter-sales.queue.v1';
const getSession=()=>JSON.parse(localStorage.getItem(sessionKey)||'null');
const token=()=>getSession()?.token||null;
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const today=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const clean=v=>String(v||'').trim().replace(/\s+/g,' ');
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uuid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;

async function request(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{...headers,...(options.headers||{})}});const text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw Error(data?.message||data?.hint||`Request failed (${r.status})`);return data}
const rpc=(name,body)=>request(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)});
function notify(message){const host=$('#toastRegion');if(!host)return;const row=document.createElement('div');row.className='toast';row.textContent=message;host.append(row);setTimeout(()=>row.remove(),3200)}

const state={menu:[],cart:new Map(),paymentMode:'cash',mode:'items',syncing:false,pickerActive:false};

function inject(){const tabs=$('.top-tabs'),main=$('#mainContent');if(!tabs||!main||$('#counterTab'))return;
  const tab=document.createElement('button');tab.id='counterTab';tab.className='tab';tab.type='button';tab.innerHTML='⚡<span>Counter</span>';tabs.prepend(tab);
  const view=document.createElement('section');view.id='counterView';view.className='counter-view view';view.hidden=true;view.innerHTML=`
    <section class="card counter-overview"><div class="counter-title"><div><p class="eyebrow">Fast walk-in billing</p><h2>Counter sale</h2></div><span id="counterSync" class="counter-sync">Synced</span></div><div class="counter-kpis"><article><span>Today</span><b id="counterTodayTotal">₹0.00</b></article><article><span>Cash</span><b id="counterTodayCash">₹0.00</b></article><article><span>UPI</span><b id="counterTodayUpi">₹0.00</b></article></div></section>
    <section class="counter-mode-switch" aria-label="Counter sale type"><button id="counterItemMode" class="active" type="button"><span>▤</span><b>Item sale</b><small>Choose from menu</small></button><button id="counterQuickMode" type="button"><span>⚡</span><b>Quick amount</b><small>Rush billing</small></button></section>
    <div id="counterItemFlow" class="counter-flow">
      <section class="card counter-quick-menu-search"><div class="section-head"><div><p class="eyebrow">Fast item entry</p><h2>Quick search menu items</h2></div></div><div class="counter-quick-search-input"><span>⌕</span><input id="counterQuickMenuSearch" type="search" autocomplete="off" placeholder="Type item or category"><button id="counterQuickMenuClear" type="button" aria-label="Clear search" hidden>×</button></div><div id="counterQuickMenuResults" class="counter-quick-search-results" hidden></div></section>
      <button id="counterOpenPicker" class="card counter-picker-trigger" type="button"><span class="counter-picker-icon">▦</span><div><b>Browse categories</b><small>Open the complete category picker and menu search</small></div><strong>＋</strong></button>
      <section class="card counter-cart"><div class="section-head"><div><p class="eyebrow">Current sale</p><h2>Selected items</h2></div><button id="counterClearCart" class="text-btn danger" type="button">Clear</button></div><div id="counterCartList" class="counter-cart-list"></div><div class="counter-total"><span>Total</span><b id="counterTotal">₹0.00</b></div></section>
    </div>
    <section id="counterQuickFlow" class="card counter-quick-screen" hidden><div class="counter-quick-intro"><span>⚡</span><div><p class="eyebrow">Rush mode</p><h2>Quick amount sale</h2><small>Enter the final bill total and save in seconds.</small></div></div><label class="counter-money-field"><span>Complete bill amount</span><div><b>₹</b><input id="counterQuickAmount" type="number" min="0.01" step="0.01" inputmode="decimal" placeholder="0.00"></div></label><label class="counter-note-field"><span>Sale note <small>Optional</small></span><textarea id="counterQuickNote" maxlength="160" rows="3" placeholder="Example: Lunch rush counter sale"></textarea><small id="counterNoteCount">0 / 160</small></label></section>
    <section class="card counter-payment"><div class="section-head"><div><p class="eyebrow">Immediate payment</p><h2>Payment mode</h2></div></div><div class="counter-payment-modes"><button data-mode="cash" class="active" type="button">Cash</button><button data-mode="upi" type="button">UPI</button><button data-mode="split" type="button">Split</button></div><div id="counterSplit" class="counter-split" hidden><label><span>Cash amount</span><input id="counterCashAmount" type="number" min="0" step="0.01" inputmode="decimal"></label><label><span>UPI amount</span><input id="counterUpiAmount" type="number" min="0" step="0.01" inputmode="decimal"></label></div><button id="counterSave" class="btn primary counter-save" type="button">Save & new sale</button></section>
    <section class="card counter-recent"><div class="section-head"><div><p class="eyebrow">Today</p><h2>Recent counter sales</h2></div><button id="counterRefresh" class="icon-btn" type="button">↻</button></div><div id="counterRecent" class="counter-recent-list"></div></section>`;
  main.prepend(view);bind(tab);loadMenu();refreshSummary();updateSync();processQueue();renderCart();
}

function bind(tab){tab.addEventListener('click',activateCounter);$$('.top-tabs .tab:not(#counterTab)').forEach(b=>b.addEventListener('click',deactivateCounter));
  $('#counterItemMode').onclick=()=>setCounterMode('items');$('#counterQuickMode').onclick=()=>setCounterMode('quick');$('#counterOpenPicker').onclick=openCounterPicker;
  $('#counterQuickMenuSearch').addEventListener('input',renderQuickMenuSearch);$('#counterQuickMenuSearch').addEventListener('focus',renderQuickMenuSearch);$('#counterQuickMenuClear').onclick=clearQuickMenuSearch;
  $('#counterClearCart').onclick=clearCart;$('#counterRefresh').onclick=()=>{loadMenu();refreshSummary();processQueue()};
  $$('.counter-payment-modes button').forEach(b=>b.onclick=()=>setPaymentMode(b.dataset.mode));
  $('#counterSave').onclick=saveSale;$('#counterCashAmount').addEventListener('input',syncSplit);$('#counterUpiAmount').addEventListener('input',syncSplit);
  $('#counterQuickAmount').addEventListener('input',()=>{updateTotal();syncSplit()});$('#counterQuickNote').addEventListener('input',()=>$('#counterNoteCount').textContent=`${$('#counterQuickNote').value.length} / 160`);
  window.addEventListener('online',processQueue);document.addEventListener('mainstreet-role-ready',updateSync);
  document.addEventListener('click',handlePickerClick,true);document.addEventListener('click',event=>{if(!event.target.closest('.counter-quick-menu-search'))hideQuickMenuResults()});['#menuDialog','#itemDialog'].forEach(s=>$(s)?.addEventListener('close',finishCounterPicker));
}
function activateCounter(){const view=$('#counterView');if(!view)return;$$('.top-tabs .tab').forEach(x=>x.classList.toggle('active',x.id==='counterTab'));['#invoiceView','#paymentView','#reportView'].forEach(s=>{const el=$(s);if(el)el.hidden=true});$('#transactionHeader').hidden=true;$('#actionBar').hidden=true;view.hidden=false;refreshSummary();processQueue()}
function deactivateCounter(){const view=$('#counterView');if(view)view.hidden=true;$('#counterTab')?.classList.remove('active');finishCounterPicker();hideQuickMenuResults()}
function setCounterMode(mode){state.mode=mode;const quick=mode==='quick';$('#counterItemMode').classList.toggle('active',!quick);$('#counterQuickMode').classList.toggle('active',quick);$('#counterItemFlow').hidden=quick;$('#counterQuickFlow').hidden=!quick;$('#counterSave').textContent=quick?'Save quick sale':'Save & new sale';updateTotal();if(quick){hideQuickMenuResults();setTimeout(()=>$('#counterQuickAmount')?.focus(),80)}}

async function loadMenu(){try{const rows=await request('menu_items?select=id,category,name,half_rate,full_rate&is_active=eq.true&order=category.asc,name.asc');state.menu=(rows||[]).map(r=>({id:r.id,category:r.category,name:r.name,halfRate:r.half_rate==null?null:Number(r.half_rate),fullRate:Number(r.full_rate)}));renderQuickMenuSearch()}catch(e){notify(e.message)}}
function renderQuickMenuSearch(){const input=$('#counterQuickMenuSearch'),host=$('#counterQuickMenuResults'),clear=$('#counterQuickMenuClear');if(!input||!host)return;const q=clean(input.value).toLowerCase();clear.hidden=!q;if(!q){host.hidden=true;host.innerHTML='';return}const rows=state.menu.filter(x=>(x.name+' '+x.category).toLowerCase().includes(q)).slice(0,8);host.innerHTML=rows.length?rows.map(item=>`<div class="counter-quick-search-row"><div><b>${safe(item.name)}</b><small>${safe(item.category)} · ${item.halfRate!=null?`H ${money(item.halfRate)} · `:''}F ${money(item.fullRate)}</small></div><div class="counter-quick-search-actions">${item.halfRate!=null?`<button type="button" data-quick-id="${safe(item.id)}" data-quick-part="half">H</button>`:''}<button type="button" data-quick-id="${safe(item.id)}" data-quick-part="full">F</button></div></div>`).join(''):'<div class="counter-quick-search-empty">No matching menu item</div>';host.hidden=false;host.querySelectorAll('[data-quick-id]').forEach(button=>button.onclick=()=>{addItem(button.dataset.quickId,button.dataset.quickPart);button.classList.add('counter-added');setTimeout(()=>button.classList.remove('counter-added'),240);$('#counterQuickMenuSearch').focus()})}
function clearQuickMenuSearch(){const input=$('#counterQuickMenuSearch');if(!input)return;input.value='';$('#counterQuickMenuClear').hidden=true;hideQuickMenuResults();input.focus()}
function hideQuickMenuResults(){const host=$('#counterQuickMenuResults');if(host)host.hidden=true}
function openCounterPicker(){state.pickerActive=true;document.body.classList.add('counter-picker-active');const dialog=$('#menuDialog');if(!dialog)return notify('Item picker unavailable');$('#menuSearch').value='';$('#clearMenuSearch').hidden=true;$('#menuBack')?.click();if(!dialog.open)dialog.showModal();updatePickerBadge()}
function finishCounterPicker(){if($('#menuDialog')?.open||$('#itemDialog')?.open)return;state.pickerActive=false;document.body.classList.remove('counter-picker-active');$('#counterPickerBadge')?.remove()}
function updatePickerBadge(){if(!state.pickerActive)return;const header=$('#menuDialog .sheet-header');if(!header)return;let badge=$('#counterPickerBadge');if(!badge){badge=document.createElement('span');badge.id='counterPickerBadge';badge.className='counter-picker-badge';header.append(badge)}badge.textContent=`${state.cart.size} selected · ${money(cartTotal())}`}
function handlePickerClick(event){if(!state.pickerActive)return;const target=event.target.closest('button');if(!target)return;if(target.matches('#doneMenu,#closeMenu,#doneItemDialog,#closeItemDialog')){setTimeout(()=>{$('#itemDialog')?.open&&$('#itemDialog').close();$('#menuDialog')?.open&&$('#menuDialog').close();finishCounterPicker()},0);return}if(!target.matches('.half,.full'))return;const row=target.closest('.menu-item');if(!row)return;event.preventDefault();event.stopImmediatePropagation();const name=clean(row.querySelector(':scope > div:first-child b')?.textContent);const text=clean(row.querySelector(':scope > div:first-child small')?.textContent);const prices=[...text.matchAll(/₹([\d,.]+)/g)].map(x=>Number(x[1].replace(/,/g,'')));const fullRate=prices.at(-1);const item=state.menu.find(x=>clean(x.name)===name&&Number(x.fullRate)===Number(fullRate));if(!item)return notify('Unable to match this menu item');addItem(item.id,target.classList.contains('half')?'half':'full');target.classList.add('counter-added');setTimeout(()=>target.classList.remove('counter-added'),240);updatePickerBadge()}

function addItem(id,part){const item=state.menu.find(x=>x.id===id);if(!item)return;const row=state.cart.get(id)||{...item,halfQty:0,fullQty:0};row[part+'Qty']++;state.cart.set(id,row);renderCart()}
function reduceItem(id){const row=state.cart.get(id);if(!row)return;if(row.fullQty>0)row.fullQty--;else if(row.halfQty>0)row.halfQty--;if(!row.fullQty&&!row.halfQty)state.cart.delete(id);else state.cart.set(id,row);renderCart();updatePickerBadge()}
function removeItem(id){state.cart.delete(id);renderCart();updatePickerBadge()}
function itemAmount(x){return Number((((x.halfRate||0)*x.halfQty)+(x.fullRate*x.fullQty)).toFixed(2))}
function cartTotal(){return [...state.cart.values()].reduce((s,x)=>s+itemAmount(x),0)}
function saleTotal(){return state.mode==='quick'?Number($('#counterQuickAmount')?.value||0):cartTotal()}
function renderCart(){const host=$('#counterCartList');if(!host)return;host.innerHTML=state.cart.size?[...state.cart.values()].map(x=>`<div class="counter-cart-row"><div><b>${safe(x.name)}</b><small>${x.halfQty?`H × ${x.halfQty}`:''}${x.halfQty&&x.fullQty?' · ':''}${x.fullQty?`F × ${x.fullQty}`:''}</small></div><div class="counter-cart-controls"><button type="button" data-action="minus" data-id="${safe(x.id)}">−</button><button type="button" data-action="remove" data-id="${safe(x.id)}">×</button><strong>${money(itemAmount(x))}</strong></div></div>`).join(''):'<div class="counter-empty">Search an item above or browse categories.</div>';host.querySelectorAll('[data-action="minus"]').forEach(b=>b.onclick=()=>reduceItem(b.dataset.id));host.querySelectorAll('[data-action="remove"]').forEach(b=>b.onclick=()=>removeItem(b.dataset.id));updateTotal()}
function updateTotal(){const total=saleTotal();$('#counterTotal')&&($('#counterTotal').textContent=money(total));if(state.paymentMode==='cash'){$('#counterCashAmount').value=total||'';$('#counterUpiAmount').value=''}else if(state.paymentMode==='upi'){$('#counterUpiAmount').value=total||'';$('#counterCashAmount').value=''}else syncSplit()}
function clearCart(){state.cart.clear();$('#counterQuickAmount').value='';$('#counterQuickNote').value='';$('#counterNoteCount').textContent='0 / 160';renderCart()}
function setPaymentMode(mode){state.paymentMode=mode;$$('.counter-payment-modes button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#counterSplit').hidden=mode!=='split';updateTotal()}
function syncSplit(){if(state.paymentMode!=='split')return;const total=saleTotal(),cash=Number($('#counterCashAmount').value||0);if(document.activeElement===$('#counterCashAmount'))$('#counterUpiAmount').value=Math.max(0,total-cash).toFixed(2);else if(document.activeElement===$('#counterUpiAmount'))$('#counterCashAmount').value=Math.max(0,total-Number($('#counterUpiAmount').value||0)).toFixed(2)}

function queue(){return JSON.parse(localStorage.getItem(queueKey)||'[]')}
function setQueue(rows){localStorage.setItem(queueKey,JSON.stringify(rows));updateSync()}
function buildPayload(){const total=saleTotal();if(total<=0)throw Error(state.mode==='quick'?'Enter the complete bill amount':'Select at least one item');let cash=0,upi=0;if(state.paymentMode==='cash')cash=total;else if(state.paymentMode==='upi')upi=total;else{cash=Number($('#counterCashAmount').value||0);upi=Number($('#counterUpiAmount').value||0);if(Number((cash+upi).toFixed(2))!==Number(total.toFixed(2)))throw Error('Cash and UPI amounts must equal sale total')}return {p_token:null,p_client_reference:uuid(),p_sale_date:today(),p_payment_mode:state.paymentMode,p_entry_type:state.mode==='quick'?'quick_amount':'item_sale',p_gross_amount:total,p_cash_amount:cash,p_upi_amount:upi,p_items:state.mode==='quick'?[]:[...state.cart.values()].map(x=>({menu_item_id:x.id,item_name:x.name,category:x.category,half_qty:x.halfQty,full_qty:x.fullQty,half_rate:x.halfRate,full_rate:x.fullRate,amount:itemAmount(x)})),p_note:state.mode==='quick'?clean($('#counterQuickNote').value):''}}
async function saveSale(){const btn=$('#counterSave');try{const payload=buildPayload(),rows=queue();rows.push({id:payload.p_client_reference,payload,createdAt:new Date().toISOString(),attempts:0});setQueue(rows);clearCart();btn.textContent='Saved';notify('Counter sale saved. Ready for next customer.');setTimeout(()=>btn.textContent=state.mode==='quick'?'Save quick sale':'Save & new sale',900);processQueue()}catch(e){notify(e.message)}}
async function processQueue(){if(state.syncing||!navigator.onLine||!token())return;state.syncing=true;updateSync();let rows=queue();for(const row of [...rows]){try{row.payload.p_token=token();await rpc('create_counter_sale',row.payload);rows=rows.filter(x=>x.id!==row.id);setQueue(rows)}catch(e){row.attempts=(row.attempts||0)+1;row.lastError=e.message;setQueue(rows);if(/session|permission|database upgrade|required/i.test(e.message))break}}state.syncing=false;updateSync();refreshSummary()}
function updateSync(){const el=$('#counterSync');if(!el)return;const count=queue().length;el.classList.toggle('pending',count>0||state.syncing);el.textContent=state.syncing?'Syncing…':count?`${count} pending`:'Synced'}
async function refreshSummary(){if(!token())return;try{const t=today(),[s,recent]=await Promise.all([rpc('get_counter_sales_summary',{p_token:token(),p_from:t,p_to:t}),rpc('get_recent_counter_sales',{p_token:token(),p_from:t,p_to:t})]);$('#counterTodayTotal').textContent=money(s?.total_sales);$('#counterTodayCash').textContent=money(s?.cash_sales);$('#counterTodayUpi').textContent=money(s?.upi_sales);renderRecent(recent||[])}catch(e){if(!/does not exist|PGRST|42883/i.test(e.message))notify(e.message)}}
function renderRecent(rows){const host=$('#counterRecent');if(!host)return;host.innerHTML=rows.length?rows.slice(0,20).map(x=>`<div class="counter-recent-row"><div><b>${safe(x.sale_no)}</b><small>${x.entry_type==='quick_amount'?'Quick amount':'Item sale'} · ${safe(x.payment_mode.toUpperCase())} · ${new Date(x.created_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</small></div><strong>${money(x.gross_amount)}</strong></div>`).join(''):'<div class="counter-empty">No counter sales recorded today</div>'}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();