export const MENU_ITEMS = [
  {"id":"menu-001","category":"Starters","name":"Manchurian Dry","fullRate":140},
  {"id":"menu-002","category":"Starters","name":"Chilli Paneer","fullRate":180},
  {"id":"menu-003","category":"Starters","name":"Honey Chilli Potato","fullRate":140},
  {"id":"menu-004","category":"Starters","name":"Manchurian Gravy","fullRate":140},
  {"id":"menu-005","category":"Fried Rice","name":"Fried Rice","fullRate":130},
  {"id":"menu-006","category":"Fried Rice","name":"Manchurian Fried Rice","fullRate":150},
  {"id":"menu-007","category":"Fried Rice","name":"Paneer Fried Rice","fullRate":170},
  {"id":"menu-008","category":"Fried Rice","name":"Schezwan Fried Rice","fullRate":130},
  {"id":"menu-009","category":"Fried Rice","name":"All Mix Fried Rice","fullRate":170},
  {"id":"menu-010","category":"Noodles","name":"Veg Noodles","fullRate":110},
  {"id":"menu-011","category":"Noodles","name":"Manchurian Noodles","fullRate":150},
  {"id":"menu-012","category":"Noodles","name":"Schezwan Noodles","fullRate":150},
  {"id":"menu-013","category":"Noodles","name":"Paneer Noodles","fullRate":170},
  {"id":"menu-014","category":"Noodles","name":"Hakka Noodles","fullRate":130},
  {"id":"menu-015","category":"Pasta","name":"Red Sauce Pasta","fullRate":150},
  {"id":"menu-016","category":"Pasta","name":"White Sauce Pasta","fullRate":130},
  {"id":"menu-017","category":"Burgers","name":"Aloo Tikki Burger","fullRate":70},
  {"id":"menu-018","category":"Burgers","name":"Veg Burger","fullRate":80},
  {"id":"menu-019","category":"Burgers","name":"Paneer Burger","fullRate":100},
  {"id":"menu-020","category":"Burgers","name":"Cheese Burger","fullRate":120},
  {"id":"menu-021","category":"Sandwiches","name":"Veg Sandwich","fullRate":70},
  {"id":"menu-022","category":"Sandwiches","name":"Veg Grilled Sandwich","fullRate":80},
  {"id":"menu-023","category":"Sandwiches","name":"Schezwan Grilled Sandwich","fullRate":80},
  {"id":"menu-024","category":"Sandwiches","name":"Paneer Sandwich","fullRate":90},
  {"id":"menu-025","category":"Sandwiches","name":"Cheese Grilled Sandwich","fullRate":100},
  {"id":"menu-026","category":"Snacks/Fries","name":"Bun Maska","fullRate":60},
  {"id":"menu-027","category":"Snacks/Fries","name":"Plain French Fries","fullRate":70},
  {"id":"menu-028","category":"Snacks/Fries","name":"Masala Fries","fullRate":80},
  {"id":"menu-029","category":"Snacks/Fries","name":"Peri Peri Fries","fullRate":90},
  {"id":"menu-030","category":"Snacks/Fries","name":"Cheese Fries","fullRate":100},
  {"id":"menu-031","category":"Maggi","name":"Plain Maggi","fullRate":40},
  {"id":"menu-032","category":"Maggi","name":"Masala Maggi","fullRate":50},
  {"id":"menu-033","category":"Maggi","name":"Vegetable Maggi","fullRate":60},
  {"id":"menu-034","category":"Maggi","name":"Schezwan Maggi","fullRate":100},
  {"id":"menu-035","category":"Maggi","name":"Paneer Maggi","fullRate":80},
  {"id":"menu-036","category":"Maggi","name":"Butter Maggi","fullRate":100},
  {"id":"menu-037","category":"Maggi","name":"Cheese Maggi","fullRate":100},
  {"id":"menu-038","category":"Momos","name":"Veg Momos","fullRate":50},
  {"id":"menu-039","category":"Momos","name":"Fried Momos","fullRate":60},
  {"id":"menu-040","category":"Momos","name":"Paneer Momos","fullRate":70},
  {"id":"menu-041","category":"Momos","name":"Paneer Fried Momos","fullRate":80},
  {"id":"menu-042","category":"Momos","name":"Crispy Paneer Momos","fullRate":100},
  {"id":"menu-043","category":"Momos","name":"Crispy Veg Momos","fullRate":80},
  {"id":"menu-044","category":"Water","name":"Water","fullRate":10},
  {"id":"menu-045","category":"Water","name":"Water","fullRate":20},
  {"id":"menu-046","category":"Cigarette","name":"Cigarette","fullRate":10},
  {"id":"menu-047","category":"Cigarette","name":"Cigarette","fullRate":15},
  {"id":"menu-048","category":"Cigarette","name":"Cigarette","fullRate":20},
  {"id":"menu-049","category":"Cigarette","name":"Cigarette","fullRate":25},
  {"id":"menu-050","category":"Cigarette","name":"Cigarette","fullRate":30},
  {"id":"menu-051","category":"Biscuits","name":"Biscuits","fullRate":7},
  {"id":"menu-052","category":"Tea","name":"Masala","fullRate":20},
  {"id":"menu-053","category":"Tea","name":"Chocolate Tea","fullRate":20},
  {"id":"menu-054","category":"Tea","name":"Elechi Tea","fullRate":20},
  {"id":"menu-055","category":"Tea","name":"Adrak Sakkar","fullRate":30},
  {"id":"menu-056","category":"Tea","name":"Gud Tea","fullRate":20},
  {"id":"menu-057","category":"Tea","name":"Gud Adrak","fullRate":30},
  {"id":"menu-058","category":"Tea","name":"Black Tea","fullRate":20},
  {"id":"menu-059","category":"Tea","name":"Lemon Tea","fullRate":20},
  {"id":"menu-060","category":"Tea","name":"Green Tea","fullRate":20},
  {"id":"menu-061","category":"Tea","name":"Sugar Free Tea","fullRate":30},
  {"id":"menu-062","category":"Tea","name":"Coffee","fullRate":30},
  {"id":"menu-063","category":"Tea","name":"Kesar Masala","fullRate":30},
  {"id":"menu-064","category":"Cold Coffee","name":"Classic Coffee","fullRate":60},
  {"id":"menu-065","category":"Cold Coffee","name":"Coffee With Ice Cream","fullRate":80},
  {"id":"menu-066","category":"Cold Coffee","name":"Blended Frappes","fullRate":70},
  {"id":"menu-068","category":"Torando","name":"Indian Spices","fullRate":50},
  {"id":"menu-069","category":"Mojito","name":"Classic Lime & Mint","fullRate":60},
  {"id":"menu-070","category":"Mojito","name":"Virgin","fullRate":60},
  {"id":"menu-071","category":"Mojito","name":"Blue Lagoon","fullRate":60},
  {"id":"menu-072","category":"Mojito","name":"Fruit-Mango/Watermelon/Jamun","fullRate":60}
];
