import { SUPABASE_ANON_KEY, SUPABASE_URL } from './supabase-config.js';

const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const headers={apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,'Content-Type':'application/json'};
const token=()=>JSON.parse(localStorage.getItem('mainstreet.staff-session.v3')||'null')?.token||null;
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const clean=v=>String(v||'').trim().replace(/\s+/g,' ');
const safe=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers,body:JSON.stringify(body)});const text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw Error(data?.message||data?.hint||`Request failed (${r.status})`);return data}
function notify(message){const box=$('#toastRegion');if(!box)return;const d=document.createElement('div');d.className='toast';d.textContent=message;box.append(d);setTimeout(()=>d.remove(),3200)}
function dateValue(d){const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}

let ledgerRows=[];
let ledgerCustomer='';

function setupOpeningBalance(){const filters=$('.ledger-filters');if(!filters||$('#openingBalanceButton'))return;const button=document.createElement('button');button.id='openingBalanceButton';button.type='button';button.className='btn secondary opening-balance-button';button.textContent='+ Opening balance';filters.append(button);button.onclick=openOpeningBalanceDialog;

const dialog=document.createElement('dialog');dialog.id='openingBalanceDialog';dialog.className='modal';dialog.innerHTML=`<form id="openingBalanceForm" class="modal-card opening-balance-card"><header><div><p class="eyebrow">Customer account setup</p><h2>Opening balance</h2></div><button id="closeOpeningBalance" type="button">×</button></header><label><span>Customer</span><input id="openingCustomer" autocomplete="off" placeholder="Type customer name" required><div id="openingSuggestions" class="opening-suggestions" hidden></div></label><label><span>Mobile</span><input id="openingPhone" inputmode="tel" placeholder="Optional"></label><div class="date-grid"><label><span>Effective date</span><input id="openingDate" type="date" required></label><label><span>Balance type</span><select id="openingType"><option value="debit">Debit — customer owes us</option><option value="credit">Credit — customer advance</option></select></label></div><label><span>Amount</span><input id="openingAmount" type="number" min="0.01" step="0.01" inputmode="decimal" required></label><label><span>Note</span><input id="openingNote" maxlength="240" placeholder="Previous account balance"></label><p class="opening-help">Saving again for the same customer updates the existing opening balance.</p><div class="modal-actions"><button id="deleteOpeningBalance" class="btn danger-btn" type="button" hidden>Delete</button><button id="cancelOpeningBalance" class="btn secondary" type="button">Cancel</button><button class="btn primary" type="submit">Save opening balance</button></div></form>`;document.body.append(dialog);
$('#openingDate').value=dateValue(new Date());
$('#closeOpeningBalance').onclick=()=>dialog.close();
$('#cancelOpeningBalance').onclick=()=>dialog.close();
$('#openingBalanceForm').onsubmit=saveOpeningBalance;
$('#deleteOpeningBalance').onclick=deleteOpeningBalance;
setupOpeningSuggestions();
replaceLedgerControls();
}

async function openOpeningBalanceDialog(){const dialog=$('#openingBalanceDialog');const name=clean($('#ledgerCustomer')?.value);$('#openingCustomer').value=name;$('#openingPhone').value=clean($('#ledgerPhone')?.value);$('#openingDate').value=dateValue(new Date());$('#openingType').value='debit';$('#openingAmount').value='';$('#openingNote').value='';$('#deleteOpeningBalance').hidden=true;if(name){try{const row=await rpc('get_customer_opening_balance',{p_token:token(),p_customer_name:name});if(row){$('#openingPhone').value=row.phone||$('#openingPhone').value;$('#openingDate').value=row.balance_date;$('#openingType').value=row.balance_type;$('#openingAmount').value=row.amount;$('#openingNote').value=row.note||'';$('#deleteOpeningBalance').hidden=false}}catch(e){notify(e.message)}}dialog.showModal()}

function setupOpeningSuggestions(){const input=$('#openingCustomer'),box=$('#openingSuggestions');let timer;input.addEventListener('input',()=>{clearTimeout(timer);const q=clean(input.value);if(q.length<2){box.hidden=true;return}timer=setTimeout(async()=>{try{const rows=await rpc('search_customers',{p_token:token(),p_query:q})||[];box.innerHTML=rows.map(r=>`<button type="button" data-name="${safe(r.name)}" data-phone="${safe(r.phone||'')}"><b>${safe(r.name)}</b><small>${money(r.balance)}</small></button>`).join('');box.hidden=!rows.length;$$('#openingSuggestions button').forEach(b=>b.onclick=async()=>{$('#openingCustomer').value=b.dataset.name;$('#openingPhone').value=b.dataset.phone||'';box.hidden=true;try{const row=await rpc('get_customer_opening_balance',{p_token:token(),p_customer_name:b.dataset.name});if(row){$('#openingDate').value=row.balance_date;$('#openingType').value=row.balance_type;$('#openingAmount').value=row.amount;$('#openingNote').value=row.note||'';$('#deleteOpeningBalance').hidden=false}else $('#deleteOpeningBalance').hidden=true}catch{}})}catch{box.hidden=true}},180)})}

async function saveOpeningBalance(e){e.preventDefault();const submit=e.submitter;submit.disabled=true;try{await rpc('upsert_customer_opening_balance',{p_token:token(),p_customer_name:clean($('#openingCustomer').value),p_customer_phone:clean($('#openingPhone').value),p_balance_date:$('#openingDate').value,p_balance_type:$('#openingType').value,p_amount:Number($('#openingAmount').value),p_note:clean($('#openingNote').value)});$('#openingBalanceDialog').close();$('#ledgerCustomer').value=clean($('#openingCustomer').value);$('#ledgerPhone').value=clean($('#openingPhone').value);notify('Opening balance saved');document.querySelector('#refreshCustomerSummary')?.click();await loadLedger()}catch(err){notify(err.message)}finally{submit.disabled=false}}

async function deleteOpeningBalance(){const name=clean($('#openingCustomer').value);if(!name||!confirm(`Delete opening balance for ${name}?`))return;try{await rpc('delete_customer_opening_balance',{p_token:token(),p_customer_name:name});$('#openingBalanceDialog').close();notify('Opening balance deleted');document.querySelector('#refreshCustomerSummary')?.click();await loadLedger()}catch(err){notify(err.message)}}

function replaceLedgerControls(){[['generateLedger','Generate ledger',loadLedger],['ledgerPdf','PDF',exportPdf],['ledgerJpg','JPG',downloadJpg],['ledgerShare','Share',shareLedger]].forEach(([id,label,handler])=>{const old=$('#'+id);if(!old)return;const fresh=old.cloneNode(true);fresh.textContent=label;old.replaceWith(fresh);fresh.addEventListener('click',handler)})}

async function loadLedger(){ledgerCustomer=clean($('#ledgerCustomer')?.value);if(!ledgerCustomer)return notify('Select a customer');try{ledgerRows=await rpc('get_customer_ledger_detailed',{p_token:token(),p_customer_name:ledgerCustomer,p_from:$('#ledgerFrom').value,p_to:$('#ledgerTo').value})||[];renderLedger()}catch(err){notify(err.message)}}

function rowKind(row){if(row.transaction_type==='invoice')return{label:'INVOICE',debit:Number(row.amount),credit:0,cls:'invoice'};if(row.transaction_type==='payment')return{label:'PAYMENT',debit:0,credit:Number(row.amount),cls:'payment'};if(row.transaction_type==='opening_debit')return{label:'OPENING DR',debit:Number(row.amount),credit:0,cls:'opening-debit'};return{label:'OPENING CR',debit:0,credit:Number(row.amount),cls:'opening-credit'}}
function itemText(row){if(row.transaction_type.startsWith('opening_'))return row.note||'Opening account balance';return (row.items||[]).map(i=>`${i.item_name}${Number(i.half_qty)?` · H×${i.half_qty}`:''}${Number(i.full_qty)?` · F×${i.full_qty}`:''}`).join(' | ')||(row.note||'Payment received')}
function renderLedger(){let balance=0,debitTotal=0,creditTotal=0;const html=ledgerRows.map(row=>{const k=rowKind(row);balance+=k.debit-k.credit;debitTotal+=k.debit;creditTotal+=k.credit;return `<tr class="${k.cls}-row-ledger"><td>${safe(row.transaction_date)}</td><td><span class="ledger-type ${k.cls}">${k.label}</span><strong>${safe(row.reference)}</strong><div class="ledger-items-detail">${safe(itemText(row))}</div></td><td class="dr">${k.debit?money(k.debit):'—'}</td><td class="cr">${k.credit?money(k.credit):'—'}</td><td><b class="${balance>0?'balance-debit':'balance-credit'}">${money(balance)}</b></td></tr>`}).join('');$('#ledgerSummary').innerHTML='';$('#ledgerList').innerHTML=`<section class="premium-ledger"><header class="ledger-brand"><img src="./assets/mainstreet-logo.svg" alt="Mainstreet"><div><p>MAINSTREET MEALS & COFFEE</p><h3>Customer Account Statement</h3><span>Invoice, payment and opening balance ledger</span></div></header><section class="ledger-party"><div><span>Customer</span><b>${safe(ledgerCustomer)}</b><small>${safe($('#ledgerPhone').value||'Mobile not recorded')}</small></div><div><span>Statement period</span><b>${safe($('#ledgerFrom').value)} — ${safe($('#ledgerTo').value)}</b><small>Generated ${new Date().toLocaleString('en-IN')}</small></div></section><div class="ledger-balance-card"><div><span>Total debit</span><b class="dr">${money(debitTotal)}</b></div><div><span>Total credit</span><b class="cr">${money(creditTotal)}</b></div><div><span>Closing balance</span><b class="${balance>0?'balance-debit':'balance-credit'}">${money(balance)}</b></div><div><span>Entries</span><b>${ledgerRows.length}</b></div></div><div class="ledger-table-wrap"><table class="ledger-table"><thead><tr><th>Date</th><th>Particulars</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>${html||'<tr><td class="ledger-empty" colspan="5">No transactions found</td></tr>'}</tbody></table></div><footer class="ledger-document-footer"><span>Debit: opening due/invoice</span><span>Credit: opening advance/payment</span><b>Mainstreet Meals & Coffee</b></footer></section>`}

function wrap(ctx,text,width){const out=[];let line='';for(const word of String(text||'').split(/\s+/)){const t=line?line+' '+word:word;if(ctx.measureText(t).width>width&&line){out.push(line);line=word}else line=t}if(line)out.push(line);return out}
async function buildCanvas(){if(!ledgerRows.length)throw Error('Generate ledger first');const width=1400;const heights=ledgerRows.map(r=>Math.max(78,58+Math.ceil(itemText(r).length/75)*22));const height=Math.max(900,470+heights.reduce((a,b)=>a+b,0)+120);const c=document.createElement('canvas');c.width=width;c.height=height;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,width,height);x.fillStyle='#111318';x.fillRect(0,0,width,145);x.fillStyle='#ff7a1a';x.fillRect(0,141,width,4);x.fillStyle='#fff';x.font='700 34px Arial';x.fillText('MAINSTREET MEALS & COFFEE',55,60);x.font='700 46px Arial';x.fillText('Customer Account Statement',55,112);x.fillStyle='#f4f5f7';x.fillRect(0,145,width,150);x.fillStyle='#5d6570';x.font='600 18px Arial';x.fillText('CUSTOMER',55,184);x.fillText('STATEMENT PERIOD',760,184);x.fillStyle='#15171b';x.font='700 30px Arial';x.fillText(ledgerCustomer,55,224);x.font='600 23px Arial';x.fillText(`${$('#ledgerFrom').value} to ${$('#ledgerTo').value}`,760,224);x.fillStyle='#68707a';x.font='20px Arial';x.fillText($('#ledgerPhone').value||'Mobile not recorded',55,258);let debit=0,credit=0,balance=0;ledgerRows.forEach(r=>{const k=rowKind(r);debit+=k.debit;credit+=k.credit;balance+=k.debit-k.credit});[['TOTAL DEBIT',debit,'#b42335'],['TOTAL CREDIT',credit,'#087f5b'],['CLOSING BALANCE',balance,balance>0?'#b42335':'#087f5b']].forEach((v,i)=>{const left=55+i*435;x.fillStyle='#f7f8fa';x.fillRect(left,315,400,105);x.fillStyle='#68707a';x.font='600 16px Arial';x.fillText(v[0],left+20,348);x.fillStyle=v[2];x.font='700 30px Arial';x.fillText(money(v[1]),left+20,392)});let y=455;x.fillStyle='#22252b';x.fillRect(55,y,width-110,48);x.fillStyle='#fff';x.font='700 17px Arial';[['DATE',72],['PARTICULARS',250],['DEBIT',950],['CREDIT',1090],['BALANCE',1235]].forEach(([t,p])=>x.fillText(t,p,y+31));y+=48;balance=0;ledgerRows.forEach((r,i)=>{const k=rowKind(r);balance+=k.debit-k.credit;const h=heights[i];x.fillStyle=k.debit?'#fff5f6':'#f1fbf6';x.fillRect(55,y,width-110,h);x.strokeStyle='#e2e5e9';x.beginPath();x.moveTo(55,y+h);x.lineTo(width-55,y+h);x.stroke();x.fillStyle='#333840';x.font='600 18px Arial';x.fillText(r.transaction_date,72,y+31);x.fillStyle=k.debit?'#b42335':'#087f5b';x.font='700 16px Arial';x.fillText(k.label,250,y+27);x.fillStyle='#17191d';x.font='700 18px Arial';x.fillText(r.reference,390,y+27);x.fillStyle='#4f5660';x.font='17px Arial';wrap(x,itemText(r),620).slice(0,3).forEach((line,j)=>x.fillText(line,250,y+52+j*22));x.fillStyle='#b42335';x.font='700 19px Arial';x.fillText(k.debit?money(k.debit):'—',950,y+31);x.fillStyle='#087f5b';x.fillText(k.credit?money(k.credit):'—',1090,y+31);x.fillStyle=balance>0?'#b42335':'#087f5b';x.fillText(money(balance),1235,y+31);y+=h});return c}
async function imageFile(){const c=await buildCanvas();const blob=await new Promise(resolve=>c.toBlob(resolve,'image/jpeg',.94));return new File([blob],`${ledgerCustomer.replace(/[^a-z0-9]+/gi,'-')}-ledger.jpg`,{type:'image/jpeg'})}
async function downloadJpg(){try{const f=await imageFile();const u=URL.createObjectURL(f);const a=document.createElement('a');a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}catch(e){notify(e.message)}}
async function exportPdf(){if(!window.jspdf)return notify('PDF library loading');try{const c=await buildCanvas();const {jsPDF}=window.jspdf;const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});const img=c.toDataURL('image/jpeg',.94),w=210,h=c.height*w/c.width;let offset=0;while(offset<h){if(offset)doc.addPage();doc.addImage(img,'JPEG',0,-offset,w,h);offset+=297}doc.save(`${ledgerCustomer.replace(/[^a-z0-9]+/gi,'-')}-ledger.pdf`)}catch(e){notify(e.message)}}
async function shareLedger(){try{const f=await imageFile();if(navigator.canShare?.({files:[f]})){await navigator.share({title:'Mainstreet Customer Account Statement',text:`Account statement for ${ledgerCustomer}`,files:[f]})}else{await downloadJpg();notify('Ledger downloaded for sharing')}}catch(e){if(e.name!=='AbortError')notify(e.message)}}

document.querySelector('#openLedger')?.addEventListener('click',()=>setTimeout(setupOpeningBalance,100));
setTimeout(()=>{if($('#ledgerDialog'))setupOpeningBalance()},300);
