import { SUPABASE_ANON_KEY, SUPABASE_URL } from './supabase-config.js';
const $=s=>document.querySelector(s);
const headers={apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,'Content-Type':'application/json'};
const session=()=>JSON.parse(localStorage.getItem('mainstreet.staff-session.v3')||'null');
const token=()=>session()?.token||null;
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers,body:JSON.stringify(body)});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.hint||'Request failed');return d}
function notify(message){const box=$('#toastRegion');if(!box)return;const row=document.createElement('div');row.className='toast';row.textContent=message;box.append(row);setTimeout(()=>row.remove(),3200)}
function dateValue(date){const d=new Date(date);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}

let currentRole=session()?.user_role||'';
let currentName=session()?.user_name||'';
async function resolveRole(){try{const rows=await rpc('get_current_staff',{p_token:token()});const u=Array.isArray(rows)?rows[0]:rows;if(u){currentRole=u.user_role;currentName=u.user_name;const s=session()||{};localStorage.setItem('mainstreet.staff-session.v3',JSON.stringify({...s,user_role:currentRole,user_name:currentName}))}}catch{}applyRole()}
function applyRole(){document.body.dataset.role=currentRole||'operator';window.mainstreetRole=currentRole;const lockup=document.querySelector('.brand-lockup div');if(lockup&&!$('#staffRoleBadge')){const badge=document.createElement('small');badge.id='staffRoleBadge';badge.className='staff-role-badge';lockup.append(badge)}if($('#staffRoleBadge'))$('#staffRoleBadge').textContent=`${currentName||'Staff'} · ${currentRole==='admin'?'Administrator':'Operator'}`;if(currentRole==='admin')requestAnimationFrame(wireExpenseRows);else document.querySelectorAll('.expense-edit-button').forEach(button=>button.remove());document.dispatchEvent(new CustomEvent('mainstreet-role-ready',{detail:{role:currentRole,name:currentName}}))}
setTimeout(resolveRole,250);

function ensureExpenseDialog(){if($('#expenseEditDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="expenseEditDialog" class="modal"><form id="expenseEditForm" class="modal-card"><header><div><p class="eyebrow">Expense record</p><h2>Edit expense</h2></div><button id="closeExpenseEdit" type="button">×</button></header><input id="expenseEditId" type="hidden"><label><span>Date</span><input id="expenseEditDate" type="date" required></label><label><span>Category</span><input id="expenseEditCategory" required></label><label><span>Description</span><input id="expenseEditDescription" required></label><label><span>Amount</span><input id="expenseEditAmount" type="number" min="0.01" step="0.01" required></label><div class="modal-actions"><button id="deleteExpenseRecord" class="btn danger-btn" type="button">Delete</button><button class="btn primary" type="submit">Save changes</button></div></form></dialog>`);$('#closeExpenseEdit').onclick=()=>$('#expenseEditDialog').close();$('#expenseEditForm').onsubmit=saveExpenseEdit;$('#deleteExpenseRecord').onclick=deleteExpenseRecord}
function wireExpenseRows(){if(currentRole!=='admin'&&document.body.dataset.role!=='admin')return;ensureExpenseDialog();document.querySelectorAll('.expense-ledger-row[data-expense-id]').forEach(row=>{if(row.querySelector('.expense-edit-button'))return;const b=document.createElement('button');b.type='button';b.className='expense-edit-button';b.textContent='Edit';b.onclick=()=>{const d=row.dataset;$('#expenseEditId').value=d.expenseId;$('#expenseEditDate').value=d.expenseDate;$('#expenseEditCategory').value=d.expenseCategory;$('#expenseEditDescription').value=d.expenseDescription;$('#expenseEditAmount').value=d.expenseAmount;$('#expenseEditDialog').showModal()};row.append(b)})}
new MutationObserver(()=>wireExpenseRows()).observe(document.body,{childList:true,subtree:true});
document.addEventListener('mainstreet-expenses-rendered',wireExpenseRows);
document.addEventListener('mainstreet-role-ready',event=>{if(event.detail?.role==='admin')wireExpenseRows()});
async function saveExpenseEdit(e){e.preventDefault();try{await rpc('update_expense',{p_token:token(),p_id:$('#expenseEditId').value,p_expense_date:$('#expenseEditDate').value,p_category:$('#expenseEditCategory').value.trim(),p_description:$('#expenseEditDescription').value.trim(),p_amount:Number($('#expenseEditAmount').value)});$('#expenseEditDialog').close();$('#refreshExpenseLedger')?.click();$('#refreshReport')?.click();notify('Expense updated')}catch(err){notify(err.message)}}
async function deleteExpenseRecord(){if(!confirm('Delete this expense permanently?'))return;try{await rpc('delete_expense',{p_token:token(),p_id:$('#expenseEditId').value});$('#expenseEditDialog').close();$('#refreshExpenseLedger')?.click();$('#refreshReport')?.click();notify('Expense deleted')}catch(err){notify(err.message)}}

function ensureLedgerWindow(){if($('#customerLedgerWindow'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="customerLedgerWindow" class="ledger-window"><section class="ledger-window-shell"><header class="ledger-window-header"><button id="closeLedgerWindow" class="icon-btn" type="button">‹</button><div><p class="eyebrow">Customer account</p><h2 id="ledgerWindowCustomer">Customer ledger</h2><span id="ledgerWindowPhone"></span></div><strong id="ledgerWindowBalance"></strong></header><section class="ledger-window-controls"><label><span>From</span><input id="ledgerWindowFrom" type="date"></label><label><span>To</span><input id="ledgerWindowTo" type="date"></label><button id="refreshLedgerWindow" class="btn secondary" type="button">Refresh</button></section><main id="ledgerWindowContent" class="ledger-window-content"><div class="account-empty">Select a customer ledger</div></main><footer class="ledger-window-actions"><button id="ledgerWindowPdf" class="btn secondary" type="button">PDF</button><button id="ledgerWindowJpg" class="btn secondary" type="button">JPG</button><button id="ledgerWindowShare" class="btn primary" type="button">Share</button></footer></section></dialog>`);$('#closeLedgerWindow').onclick=closeLedgerWindow;$('#refreshLedgerWindow').onclick=refreshLedgerWindow;$('#ledgerWindowPdf').onclick=()=>$('#ledgerPdf')?.click();$('#ledgerWindowJpg').onclick=()=>$('#ledgerJpg')?.click();$('#ledgerWindowShare').onclick=()=>$('#ledgerShare')?.click();$('#customerLedgerWindow').addEventListener('cancel',e=>{e.preventDefault();closeLedgerWindow()})}
function closeLedgerWindow(){const list=$('#ledgerList'),summary=$('#ledgerSummary'),filters=$('.ledger-filters');if(filters&&summary&&!filters.contains(summary))filters.after(summary);if(summary&&list&&!summary.contains(list))summary.after(list);$('#customerLedgerWindow')?.close()}
function openLedgerWindow(name,phone,balance){ensureLedgerWindow();const end=new Date(),start=new Date();start.setDate(end.getDate()-29);$('#ledgerCustomer').value=name;$('#ledgerPhone').value=phone||'';$('#ledgerFrom').value=dateValue(start);$('#ledgerTo').value=dateValue(end);$('#ledgerWindowFrom').value=$('#ledgerFrom').value;$('#ledgerWindowTo').value=$('#ledgerTo').value;$('#ledgerWindowCustomer').textContent=name;$('#ledgerWindowPhone').textContent=phone||'No mobile recorded';const numeric=Number(String(balance||'').replace(/[^0-9.-]/g,''));$('#ledgerWindowBalance').textContent=money(numeric);$('#ledgerWindowBalance').className=numeric>0?'window-debit':'window-credit';$('#customerLedgerWindow').showModal();refreshLedgerWindow()}
function refreshLedgerWindow(){const from=$('#ledgerWindowFrom').value,to=$('#ledgerWindowTo').value;$('#ledgerFrom').value=from;$('#ledgerTo').value=to;$('#generateLedger').click();setTimeout(()=>{const host=$('#ledgerWindowContent'),summary=$('#ledgerSummary'),list=$('#ledgerList');host.innerHTML='';if(summary)host.append(summary);if(list)host.append(list)},350)}
document.addEventListener('click',e=>{const row=e.target.closest('.customer-summary-row');if(!row)return;e.preventDefault();e.stopImmediatePropagation();openLedgerWindow(row.dataset.name,row.dataset.phone,row.querySelector('strong')?.textContent)},true);
